---
title: "Nate's Part"
author: "Nate Ferguson"
date: "2023-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(dplyr)
```

```{r}
file_path <- "All National Parks Visitation 1904-2016.csv"
national_parks_data <- read.csv(file_path)
```
```{r}

national_parks_data$YearRaw = as.numeric(national_parks_data$YearRaw)
ggplot(national_parks_data, aes(x = YearRaw, fill = Unit.Type)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle=45, vjust=0.5, hjust=1)) +
  scale_x_continuous(breaks = seq(1904,2016,20))

```
```{r}
firstYear <- national_parks_data %>%
  filter(Unit.Type == "National Park") %>%
  group_by(Unit.Name) %>%
  filter(Year == min(Year))

ggplot(firstYear, aes(y = Visitors, x = YearRaw)) +
  geom_point() +
  theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1))
```
```{r}
ParksCreatedPerYear <- firstYear %>%
  group_by(YearRaw) %>%
  summarise(Unique_Parks = n_distinct(Parkname))

ParksCreatedPerYear

```

```{r}
totalVisitation <- national_parks_data %>%
  group_by(Unit.Type, Unit.Name) %>%
  summarize(totalVisitationPerPlace = sum(Visitors))

limitedTotalVisitation <- totalVisitation %>%
 filter(Unit.Type %in% c("National Park", "Other Designation", "Park", "National Lakeshore", "National Monument"))

ggplot(limitedTotalVisitation, aes(y = totalVisitationPerPlace, fill = Unit.Type)) +
  geom_boxplot() +
  coord_cartesian(xlim= c(-0.3,0.3)) +
  scale_x_discrete()
  
```

```{r}
statisticalView <- national_parks_data %>%
  group_by(Unit.Type) %>%
  summarise(visitorMean = mean(Visitors, na.rm = TRUE),
            visitorSD = sd(Visitors, na.rm = TRUE))
ggplot(statisticalView, aes(x = visitorMean, y = visitorSD)) +
  geom_point()

```
```{r}

summary(statisticalView)

```
